version: "3.5"

services:

##56002 - db
  postgresdb:
    image: postgres:12
    ports:
      - "56002:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgres/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "teamsmanagement"
    container_name: db
    networks: 
      - teamsmanagement

##56003 - db-pgadmin
  dbpgadmin:
    image: dpage/pgadmin4:4.15
    ports:
      - "56003:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@teamsmanagement"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    container_name: pgadmin
    volumes:
      - pg_volume:/var/lib/pgadmin
    networks: 
      - teamsmanagement

##56101 - teamsmanagement
  teamsmanagement:
    image: teamsmanagement/teamsmanagement
    build:
      context: ./../teamsmanagement
      dockerfile: ./Dockerfile
    container_name: teamsmanagement
    ports:
      - '56101:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - teamsmanagement
    depends_on:
      - postgresdb
    restart: 
      on-failure

networks:
  teamsmanagement:
    name: teamsmanagement-network

volumes:
  db_volume:
  pg_volume: